version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:

      - checkout

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile

      - run:
          name: Test Packages
          command: yarn run test:ci